# @name signup
POST http://{{host}}/api/{{version}}/user/sign/up HTTP/1.1
Content-Type: application/json

{
    "email": "test@guest.com",
    "password": "1234",
    "user_role": "user"
}

###

# @name signin
POST http://{{host}}/api/{{version}}/user/sign/in HTTP/1.1
Content-Type: application/json

{
    "email": "test@guest.com",
    "password": "1234"
}

###
@refreshToken = {{signin.response.body.tokens.refresh}}
@accessToken = {{signin.response.body.tokens.access}}


# @name signout
POST http://{{host}}/api/{{version}}/user/sign/out HTTP/1.1
Authorization: Bearer {{refreshToken}}
Content-Type: application/json
