name: 'go-environment-composite'
description: composite for go environment
# references
# - https://github.com/create-go-app/cli/blob/master/.github/workflows/testing_build.yml
# - https://staticcheck.io/docs/running-staticcheck/github-actions/
# - https://blog.kowalczyk.info/article/8dd9c2c0413047c589a321b1ccba7129/using-github-actions-with-go.html
# - https://fe-developers.kakaoent.com/2022/220106-github-actions/

inputs:
  go-version:
    description: go version
    required: false
    default: 1.17.x

runs:
  using: 'composite'

  steps:
    -
      name: Set up Go 1.x
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ inputs.go-version }}
      id: go
    -
      name: Cache Go modules
      uses: actions/cache@preview
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
