name: CommitLint

on:
  push:
    branches: [ "main" ]

  pull_request:
#    branches: [ "develop" ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      -
        name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_NOTIFY_GH_ACTIONS }}
      -
        name: trigger jenkins Job
        shell: bash
        run: |
          WEBHOOK=${{ secrets.JENKINS_WEBHOOK_URL }}
          TOKEN=${{ secrets.JENKINS_API_TOKEN }}

          curl -X POST -u admin:${TOKEN} "${WEBHOOK}job/tmp1/buildWithParameters?BUILD_DOCKER_IMAGE=true&RUN_TEST=true&PUSH_DOCKER_IMAGE=true"

