name: "test-go-source"
# references
# - https://github.com/create-go-app/cli/blob/master/.github/workflows/testing_build.yml
# - https://staticcheck.io/docs/running-staticcheck/github-actions/
# - https://blog.kowalczyk.info/article/8dd9c2c0413047c589a321b1ccba7129/using-github-actions-with-go.html
# - https://fe-developers.kakaoent.com/2022/220106-github-actions/

on:
  push:
    branches:
      - develop
    # paths:
    #   - "**.go"

  pull_request:
    branches:
      - develop
    # paths:
    #   - "**.go"
env:
  GOPROXY: "https://proxy.company.com"

jobs:
  testing:
    name: Testing build
    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        go-version: [1.17.x]
        # platform: [ubuntu-latest, windows-latest, macos-latest]
        # window와 mac에는 docker가 없어서 doctertests를 사용해 테스트 불가능
        platform: [ubuntu-latest,]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set up Go 1.x
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache Go modules
      uses: actions/cache@preview
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Test
      run: go test -vet=off -v -cover -race -timeout 120s ./...
      if: ${{ always() }}

    - name: Send slack when failed
      if: ${{ failure() }}
      uses: ./.github/actions/slack-notify
      with:
        slack_incoming_url: ${{ secrets.SLACK_NOTIFY_GH_ACTIONS }}

    - name: Send slack if completed
      if: ${{ success() }}
      uses: ./.github/actions/slack-notify
      with:
        status: success
        slack_incoming_url: ${{ secrets.SLACK_NOTIFY_GH_ACTIONS }}
