name: "test-go-source"

on:
  push:
    branches:
      - develop
    paths:
      - "**.go"
  pull_request:
    branches:
      - develop
    paths:
      - "**.go"
env:
  GOPROXY: "https://proxy.company.com"

jobs:
  testing:
    name: Tests
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
    -
      name: Check out code into the Go module directory
      uses: actions/checkout@v2
    -
      name: Prepare go environment
      uses: ./.github/actions/go
    -
      name: Test
      run: go test -vet=off -v -cover -race -timeout 120s ./...
      if: ${{ always() }}
    -
      name: Send slack when failed
      if: ${{ failure() }}
      uses: ./.github/actions/slack-notify
      with:
        slack_incoming_url: ${{ secrets.SLACK_NOTIFY_GH_ACTIONS }}
    -
      name: Send slack if completed
      if: ${{ success() }}
      uses: ./.github/actions/slack-notify
      with:
        status: success
        slack_incoming_url: ${{ secrets.SLACK_NOTIFY_GH_ACTIONS }}
